sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: sTPnF7BZdolQhKrpC7HIt0j8y0Axr0xUk6CqFmQU0MmUKf8axaIzdARGbOvJaGj8iwb+KUoABsBgsC8tb/uZN3MW4ATOsyBT9/xvjHsioeh+09oAs66qnzZ+aavmBaQsdz6+28wPQOmvuGjn9ApKTPCTAiYesVNjVkAP9xW3clcZw31tG0mkpdXUcUBTMS2Nahu6h5wMi/t2r1Huj/W4+XmjJoA6VNsOAQIIv1txNSs8xV8RnQQs8pxIcr0TpcsLAA+W1uDbbYzhCHhFuLAQkZRTYVI+l2A2zsW8csl/yMFaIMsT1/CQqAKKPRXX3YYkv55EuJPbM5Qkh/yFhj1KdxF99Uz6ig9Moj9a8sR2hng/kEl5UuAHvg6S4gXiJSDFpGN7W8GgqOr5f5xckuFr5wsYMQWSMJmhNjp5VjDcrFe2ajC3dnZDTwj522+TahK0Z3twJf95zJnKdAdU2N3Log/LcK5E+nb8MRKUYc+VLeikbXQ0KCCzUw3zfBxoYx2iYN371dZjBr1HzPSDwdZUGRsvTEey7V1XYBjeAbj9JpkwtGis3Z8QXPO12qWknLHSlqkWzetm2V9D+yKQ+Vi7hNFxeJ7co5XO6ncoVgqVtJd9KrERjcOQuLgM2tvMzrgPvFXgJBQ6O9pmVgQrPLCZb0yftEkXm9mkPFfwqxGpSuU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Voyage-au-Centre-de-la-Terre_4791
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy